# Site settings
baseurl = "/"
themesDir = "themes/"
languageCode = "en-us"
title = "6ixes"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-93514740-2"
# Disable comments by leaving disqusShortname empty
disqusShortname = "www-joshnothum-tech"

[params]
	name = "Josh Nothum presents 6ixes"
	description = "6ixes are lists of 6; They mean nothing; They are written by Josh Nothum for no reason."
	bio = "Recovering sarcast; Ensorcelled programmer; Basketball player; List maker"
	# Enter optionally your twitter account
	twitter = "https://twitter.com/josh_nothum"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "Home"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "An asipiring ironist."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/josh_nothum"
    github   = "https://www.github.com/joshnothum"
	spotify  = "https://open.spotify.com/user/joshnothum"